### ISSUE TITLE
这个仓库和 T-MVP 是什么关系？

### ISSUE THREAD

**Issue by panda912** [UCodeUStory/S-MVP#1]
比较好奇，一千多个 star，竟然没人提 issue，那我提一个吧，S-MVP 和 [T-MVP](https://github.com/north2016/T-MVP) 是什么关系呢？

**Comment by Fritz-Xu** [comment]
应该就是多了些热修复的集成和不用dtabinding吧，我看到代码重复率蛮高的，在plugin上面

**Comment by UCodeUStory** [comment]
这个项目也参考了很多MVP框架，结合自己实际项目应用，抽离出来的

**Comment by UCodeUStory** [comment]
relax 是我的一个kotlin版本组件化开发库，感兴趣可以给我多提提意见，一起来维护
